### ISSUE TITLE
Exclude puzzle inputs using .gitignore

### ISSUE THREAD

**Issue by calumx** [adrianklimek/advent-of-code-bun#1]
Hey, thanks so much for this - it's the best template I've used! Really nice work.

I almost accidentally committed my puzzle inputs which is discouraged by AoC - https://adventofcode.com/about#faq_copying.

Just wanted to suggest maybe updating the `.gitignore` if possible to avoid people making the same mistake? Maybe something like:

```
# Exclude puzzle inputs - see https://adventofcode.com/about#faq_copying

src/**/*.txt
```

?

Thanks again!

**Comment by adrianklimek** [comment]
@calumx Thank you 🙌 I've excluded input files from git!
